manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: EmbeddedRPC
      url-base: https://github.com/EmbeddedRPC
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: zephyr-v3.4.0
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - mbedtls
          - mcuboot
          - mcumgr
          - nrf_hw_models
          - segger
          - tinycbor
          - tinycrypt
          - zcbor

    - name: erpc
      remote: EmbeddedRPC
      revision: 1.10.0

  self:
    path: app
